language: java

jdk:
- oraclejdk8

install: true

script:
- ./gradlew clean build --stacktrace

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: v6PK+ODebbAFkYUglvAXCuQ8fzvqxy3Xa05JXgad32F5DHMEwJVu6g+p1boopTTjVMaHuDYsm3JidAtSvwAGMov7xoZ4uQk7Dbk3U7j0PGljl5MY5Dc2m/NARZTGEyZAhFdE96A+cjsKHSpMD87MWCXg8rCvl80P74KH9kVNU4qYdD1fzgsvNQ0RHkhyWbAHB/8DJUgphVS9KCgX3dslwhkASqc+k/wBE+uTC9yjIgoxBUSNbM1laJe50xMWAQrfCPRPv1wASuTpL6cIF/NSSiotTd4OOM5Tq5prYyEjJCog9kZVS3b+aaLD5AAE4GzUTqMpE9YaUoS/uozefR4j/b0V8YAnFalApS92OfBytD21nobKQrCJ+Prqk8y+6ALUZlYqrO2FaFT/10yBu3ybiwjJue1KEYXcsdmotd8wp81m4Ek153XG2SuQ4WKv+IajfzAWwgu8wP9dsJWfHMzn1CF1HMViWkVUMmOS6hfGo6WTe8MGBvxo1m0hptq0e9rsoHBqASXDWZr+FUQE9MXgVcGtzzF2ve7twdC2hRF8Z9ZgpvWftiLLSnyvP1BTptxH8dYWCSJKAHSdYctFGZbCj3Zk/lCtg8YdVU5cWESxIsxEf2hRlf0diKh0ph8qvY4c3ORyNLzxTG8Wmifte3EFbtWEwNtObIZeDHiainMDx5Q=
  - secure: m6wDAzOSDvb0YCo1R2opkltNxZUwXgxw+831CeLkW6X3kWRuGG4+xOhXD/U4Z3iWhU44hYTAUKQN/kxmpU6bBABRZrOnSpAapTmhSMALuJhuOAL0kIPxt0Q7IuwM6zKogJrxTMIPhu/48oLBbwLXLsEnytjs0i1VTysdd/uxaHmC6hIHqyXDbpS5Ac8WXeNm6S7ZMFEUMOi24di/VJINBq+zi79fN02h9gl7KwyejWYA685K3uUgNjchk/VsSI6zYqQHe7/yo6qJIcfyfuUJjAHZPTZQ96yJCyzjpt0teL1i6InIz51Grcuy39N5UC2nE5pBdbpEZH7nhG5cd0I1E6cFugpLXpGZbVwo9VqC07IUtwW2ibxtaJauhQDaKondERAvNts5fSqhKcBXOUIjfGO4KjZSYm2rK2jo9mzRVHJL368Gell9esL8R3cJ9dUIztfC92wH/JjvCTdjhqgGxoiNzLEDbfom8yEaoLe5Uj2YZ09t1WXCckR0tkunbgdPHZncmrJ8ZZlDwg81ttdlW+HdOYPMc9aiaI8d+MFgRDhDMK1vwHXSL4nkKaxbJ5LGVGnuO5ICUmG735feRxDBRwycgVx4L3uDEWW9ZXy8xBNfDbdti6hoXLxZYhZvlJ4tJCWCNa52jKkNQZG4CvIkMXBRduV2j5wQTgo4+5Dp4s4=

branches:
  except:
  - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.gradle
