language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean build

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: v6PK+ODebbAFkYUglvAXCuQ8fzvqxy3Xa05JXgad32F5DHMEwJVu6g+p1boopTTjVMaHuDYsm3JidAtSvwAGMov7xoZ4uQk7Dbk3U7j0PGljl5MY5Dc2m/NARZTGEyZAhFdE96A+cjsKHSpMD87MWCXg8rCvl80P74KH9kVNU4qYdD1fzgsvNQ0RHkhyWbAHB/8DJUgphVS9KCgX3dslwhkASqc+k/wBE+uTC9yjIgoxBUSNbM1laJe50xMWAQrfCPRPv1wASuTpL6cIF/NSSiotTd4OOM5Tq5prYyEjJCog9kZVS3b+aaLD5AAE4GzUTqMpE9YaUoS/uozefR4j/b0V8YAnFalApS92OfBytD21nobKQrCJ+Prqk8y+6ALUZlYqrO2FaFT/10yBu3ybiwjJue1KEYXcsdmotd8wp81m4Ek153XG2SuQ4WKv+IajfzAWwgu8wP9dsJWfHMzn1CF1HMViWkVUMmOS6hfGo6WTe8MGBvxo1m0hptq0e9rsoHBqASXDWZr+FUQE9MXgVcGtzzF2ve7twdC2hRF8Z9ZgpvWftiLLSnyvP1BTptxH8dYWCSJKAHSdYctFGZbCj3Zk/lCtg8YdVU5cWESxIsxEf2hRlf0diKh0ph8qvY4c3ORyNLzxTG8Wmifte3EFbtWEwNtObIZeDHiainMDx5Q=
    - secure: UQfBqYLsO/l/JmZ224wggTMNImZVWAQxas7/oG0d/EQUguvLwP+NtnzAxdNFRZc1wGf0JxNl432q6ZiisPVPBT2PtZ47MNmvl9uK1ALQs5QBhD7VJBndcKXzTW2KHd7meNx0wcQijQhQp5HS2WCGXvOpcQLG1J9nex7NPWBi7An7CUnk75dRlt/8toLHr5fN8EIPd0NN9Z8nUhbzBQMFlwpENW60ZbsxzAh1jpeJsYrJ6RM3YfZHngmfrLTe9nAh+oLP8SL2f9wG/eUxWfLOFN7nrScNxHZE1NijXEKvpgBnJqX17CmdXXVj2begQUewF4y0jPNzob1UstkTXhNpvMREfutddbYIV/i4bAdu+wm+NMQAamzEhmgfojwcwVn15QHpZE0yRgCriME6Q5HJTRY4MEboQfop2eaioLJ+lyAGGbLRe98yk7aUCN+mI2dDBbRgiqqOd1yQ0rpKxWnHOglGBuvuBThwW+/9NHBRqI2SrEKF30X6+We3EKL5/XTdhb66QYFqRdqG+EyCmKa6GfSl/AS64q0buYccr7QxgvGC0aU2hfhZ+3Phvmev6SiAqX85cmAqN5PySYWEIVoYr42ThAML0L1vZjKUlWYPAbzb1KAae7w4gYG6Wb3yGEI/MEZY1lrF5tbYJIa6Mpn+RMLlNjqvk99TKHxEdg5yCH4=

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
