language: java

jdk:
- oraclejdk8

install: true

script:
- ./gradlew clean build --stacktrace

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: "vsDKIPnoWy+59UyPIrc7TqY+CwfCUcjFDiYSd2TJMmxR+Q9gzckhwY42Bl4igUq78euY9lnpawYkUdZ3pX/0ic4Dg/VLl4Fj7mEwnPShRkN1vJePiKEYnamFUT30RNW9EpZmFWgWkwFWMI02ZhT99y3vADbT4czwUqDRdHnSTTvGUO+aovqFpCgu9zmw11XxKmsuujsrVeACHkmJ9cEHc0HhXLQZDBa4Qer8uYFRHfAg7+la8NSVYdU6fJEXOkU33RP83JnmxvQGnEwQ3YjZz9Ljw1AJPUzex6WfuIeeMzRm4MAwRTS5fqXWlwLjY3wqywiKx2VgsBlMiBFkvMYEavSF3jmD7ggcDY/L/xisVUM27liTjXEbc3ig1vZH0W4fAnnAr/JetHLMOOyE342IRPg7k2Ycj4b2zfbOuimXT0znwj9cA9Ygi4lJc7gAEio+4qWbE7UxzJYALogmqn51rz+xMjZPDqQ9KKLE5PGK0+iLFNig4URz79+BEkuJ3IYHnswbGZVf/A4nOuOrHKSt2SGjvbNI21/Iq6XwRaHhV2UiE1xmCMdpy6htfNJX2oTwcBlsjU/ZoTY0RP8Gij4W7+KHHqSLnr9OJPPN1CFiQujASyuEKe5bBBWgEasYN5dx4Rt0WRqm6E7wqKO/R9Ng5Ge8AcHcE+ShaTTYEn6eUiE="
  - secure: "LTYvjX491AFRXeiA0x7Y3IGYw0hUG5sGoFTkNVN2/WncyAMaw6d8kL7nSQ9lT4s393PoodKVTL5nO3MMYX/JSH8VZ+wBU9MrYVAoonRudt3A0XBGyYy4gGPHy7lHaNg4gs1ksxVXROUI06QCfVmBEHIWXvbEu9xjodWg25YIRcPmTQ3tuApWsG331+vRgEHbAHtQfqv5GxOknD0pgvb6S0qqTe/A34cue3GIRK/qXyJ6MUkTaTJjIbZqu4v2iOOUQ8CKsBeTqIQ69UxM1RQnCiXpOH9Rl725kzwRsxfEqIz0n45hgCZElY2mm2rpJJ9Q+KORRkTLyz6JZ1Axpb1AVw2ArAFZi+gwOJujV25JkUjZ7U6OT3Thbrv3T1SwvH34R67mfjcAHbL8TSq9lJvKpdKcx8RjnGqmhgC32sQAqWRaZLMM06uTAnjb5+j6YmAp1kpLX9+dboSB5qC9PZGokfQWlEJc8hdkf+mO3s2grYZ9gvojWrHvgM7ej6uAI6QH1NjCknwC4HPuRkaxd4GEBSWz8NVcrCTKAjyeSm9UryRhIfr1mznLdRzJlAW1HF1tvZ4+oIsgOgQxt8pdjWNYoY+c7dOQ8gIcCG/7BAKR5umDmcUZz39s8HkMMVHfj/9yBHix+pN9cYgBB9K+xabKxwW02M/jj/LTlb7PO99f2bk="

branches:
  except:
  - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.gradle
