language: java

jdk:
- oraclejdk8

install: true

script:
- ./gradlew clean build --stacktrace

after_success:
- .buildscript/deploy_snapshot.sh

env:
  global:
  - secure: sHBh6zajhbmiv7SNO9FyqXIlY1R8yS1rgAQYOvHZX1c6qFLRS+27fpn7B9658npAbW/WPD27O7Rsztbo1WfHW2H0W1MUJx9QUErwaWXwDfSnR5dpiuvLwFtxq6h68S3KnuDe63GLEG9lN0ZPEtlQ43utpOUUB2mSRriecjudUrhu85dszrg2TxUfcUskP2yzm59P8/7M1AgIrMKYT2tSIPTqN1gOkmgSuOHqy0UD7xWGp8CImWH9tQKzzMwqKQcRxCfqYkRnP2cROtRFfQvGGDvtdoXioBhWkId2edSsnE1vcOtAsho1EmoBV0UdUJG1gR+v35BBU4gVEMhccE1eoE8wFtKujOoiZAfZX4XtEHAXAmNc0KRJ5h6rH1Tdz3PfUvFrAaJrHJFaacRqEb+ocDoI/g8X7e5S6WT0tTMJVpCGO8wzUb5q9c8uf43efYYSzAds2PxxW5/YC7OBp9Y/Ay1dqtkO9HHtp/O1H5eGTfyMxy75unndIU4hC3fa2eDfjI/aqfNerora0vC7H6P6JCI3FuChjkJvy5cy4qtu2mMscrN/KsQ0IssxDMBcHYYKvM6mdxXkyh29k+NTIV4N7PbuY0glYvEVa2izWcpH61XNZd4yhQCrLVUtH+ZI9QXdXWAOPDHmp4E+0+PnAo3ny/fBLHmnjcHCamNry9DO/FI=
  - secure: H+P0bZzwhg6J4NqozmZ/mAm4Acxpz8V4D1pSEq0V6MVrwWPS17ao+0afM6edVOBF2YQYT4OrNm71iujU8th3bQfvuaaEkK9R/+uuvgD35n0OKxD3tXViDh6QLPq9rnhpibSQrv8YPMeEXaooAJ/+5I6avFYMVBXmsjwexyeuEiJfYcRHvxzPfe6Z/G557AgqoB+48RYZYhYvZKy4URghrpe+O5GXqAxNt1OOVWQgIne6YXlFl2m60BPJ5xq78fZajPWylGadiQoxhbfSYFXeBiZwx5bXH/6RqeGIv+ynHiCr7JqUallr9psOTdAP0qxh0o6daKY706VpTtVYRJy0uhyfkFFZKKx9aS88nIh0S8Fsja9BYmh0rb7lCa4vDU70ODbxep2Jikj95kj+2mBTjVBTmMpt45OZniTObOVTevY+OonjRjlrup9YQ5GIjgGE/biWm5WEZyqP2yqmv+o/B7Rt3gfhI1X3mf8gnLxYRKUD0hE3KJaKMRdFyLS405WjQc97xGnSsi5G2Z7DU2x8Ca1TrrYc8hS4fB+3d+iGpVHjDKqPYpZHWl4TZy9etxCRc0a9g2m8FhXWUp5uUl0VV2vlWAGrxTamNR0XmszLCSCORDZS6RC1cfnPuACfy+4LHQfHKrM5f562LDByt5v7uWkT826hTvAtR8UCf1Y7FWc=

branches:
  except:
  - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
  - $HOME/.gradle
